alias: Automate your Detector light and switch
description: ""
trigger:
  - type: motion
    platform: device
    device_id: cccbfc78f3a6f726edefcc7235e547be
    entity_id: binary_sensor.couloir_detect_1_occupancy
    domain: binary_sensor
    id: capteur1on
  - type: motion
    platform: device
    device_id: 6ea048e79e48e66c043c7ba86093fa2d
    entity_id: binary_sensor.couloir_detect_2_occupancy
    domain: binary_sensor
    id: capteur2on
  - type: motion
    platform: device
    device_id: d0fa7826b9e9d41b92290960b9f5b4b6
    entity_id: binary_sensor.0x2c1165fffed592a2_occupancy
    domain: binary_sensor
    id: capteur3on
  - type: no_motion
    platform: device
    device_id: cccbfc78f3a6f726edefcc7235e547be
    entity_id: binary_sensor.couloir_detect_1_occupancy
    domain: binary_sensor
    id: capteur1off
  - type: no_motion
    platform: device
    device_id: 6ea048e79e48e66c043c7ba86093fa2d
    entity_id: binary_sensor.couloir_detect_2_occupancy
    domain: binary_sensor
    id: capteur2off
  - type: no_motion
    platform: device
    device_id: d0fa7826b9e9d41b92290960b9f5b4b6
    entity_id: binary_sensor.0x2c1165fffed592a2_occupancy
    domain: binary_sensor
    id: capteur3off
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: capteur1on
        sequence:
          - service: light.turn_on
            data: {}
            target:
              device_id: 2fd794b2080d4190621eea362f563f23
          - service: switch.turn_on
            data: {}
            target:
              device_id: 7fef900afa217812aa145083844486d0
      - conditions:
          - condition: trigger
            id: capteur1off
          - type: is_no_motion
            condition: device
            device_id: cccbfc78f3a6f726edefcc7235e547be
            entity_id: binary_sensor.couloir_detect_1_occupancy
            domain: binary_sensor
          - type: is_no_motion
            condition: device
            device_id: 6ea048e79e48e66c043c7ba86093fa2d
            entity_id: binary_sensor.couloir_detect_2_occupancy
            domain: binary_sensor
          - type: is_no_motion
            condition: device
            device_id: d0fa7826b9e9d41b92290960b9f5b4b6
            entity_id: binary_sensor.0x2c1165fffed592a2_occupancy
            domain: binary_sensor
        sequence:
          - service: light.turn_off
            data: {}
            target:
              device_id: 2fd794b2080d4190621eea362f563f23
          - service: switch.turn_off
            data: {}
            target:
              device_id: 7fef900afa217812aa145083844486d0
      - conditions:
          - condition: trigger
            id: capteur2on
        sequence:
          - service: light.turn_on
            data: {}
            target:
              device_id: 2fd794b2080d4190621eea362f563f23
          - service: switch.turn_on
            data: {}
            target:
              device_id: 7fef900afa217812aa145083844486d0
      - conditions:
          - condition: trigger
            id: capteur2off
          - type: is_no_motion
            condition: device
            device_id: cccbfc78f3a6f726edefcc7235e547be
            entity_id: binary_sensor.couloir_detect_1_occupancy
            domain: binary_sensor
          - type: is_no_motion
            condition: device
            device_id: 6ea048e79e48e66c043c7ba86093fa2d
            entity_id: binary_sensor.couloir_detect_2_occupancy
            domain: binary_sensor
          - type: is_no_motion
            condition: device
            device_id: d0fa7826b9e9d41b92290960b9f5b4b6
            entity_id: binary_sensor.0x2c1165fffed592a2_occupancy
            domain: binary_sensor
        sequence:
          - service: light.turn_off
            data: {}
            target:
              device_id: 2fd794b2080d4190621eea362f563f23
          - service: switch.turn_off
            data: {}
            target:
              device_id: 7fef900afa217812aa145083844486d0
      - conditions:
          - condition: trigger
            id: capteur3on
        sequence:
          - service: light.turn_on
            data: {}
            target:
              device_id: 2fd794b2080d4190621eea362f563f23
          - service: switch.turn_on
            data: {}
            target:
              device_id: 7fef900afa217812aa145083844486d0
      - conditions:
          - condition: trigger
            id: capteur3off
          - type: is_no_motion
            condition: device
            device_id: cccbfc78f3a6f726edefcc7235e547be
            entity_id: binary_sensor.couloir_detect_1_occupancy
            domain: binary_sensor
          - type: is_no_motion
            condition: device
            device_id: 6ea048e79e48e66c043c7ba86093fa2d
            entity_id: binary_sensor.couloir_detect_2_occupancy
            domain: binary_sensor
          - type: is_no_motion
            condition: device
            device_id: d0fa7826b9e9d41b92290960b9f5b4b6
            entity_id: binary_sensor.0x2c1165fffed592a2_occupancy
            domain: binary_sensor
        sequence:
          - service: light.turn_off
            data: {}
            target:
              device_id: 2fd794b2080d4190621eea362f563f23
          - service: switch.turn_off
            data: {}
            target:
              device_id: 7fef900afa217812aa145083844486d0
mode: single
